name: ace
description: "An app that lets students easily view, monitor, and manage their grades and educational information."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.3.0
  firebase_database: ^11.0.4
  firebase_storage: ^12.1.2
  firebase_auth: ^5.1.3
  firebase_messaging: ^15.0.4
  firebase_analytics: ^11.2.1
  cloud_firestore: ^5.2.0

  cupertino_icons: ^1.0.6
  hive: 2.2.3
  hive_flutter: ^1.1.0
  isar_flutter_libs: ^4.0.0-dev.13
  intl: ^0.19.0
  path_provider: ^2.1.3
  flutter_native_splash: ^2.4.1
  url_launcher: ^6.3.0
  ionicons: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.11

flutter_native_splash:
  #color: ""
  #image: assets/images/splash.png
  #android: true
  #ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/images/banner/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
        - asset: assets/fonts/Lato-Black.ttf
